### ISSUE TITLE
Erreurs client

### ISSUE THREAD

**Issue by Yvem** [lemonde/angular-draganddrop#4]
L'appel à `fromJson` n'est pas entouré de try/catch.

Or cela échoue parfois :
```
2015-04-21T15:15:03.314Z
nodejs-process.version		1.52.1
clientData		Uncaught SyntaxError: Unexpected token u,https://huit.lemonde.fr/articles/33586/medias:1:1,SyntaxError: Unexpected token u
    at Object.parse (native)
    at Object.V [as fromJson] (https://huit.lemonde.fr/app/main-app.986c0ae6.js:3:28667)
    at https://huit.lemonde.fr/app/main-app.986c0ae6.js:1:3506
    at Array.reduce (native)
    at l (https://huit.lemonde.fr/app/main-app.986c0ae6.js:1:3403)
    at HTMLDivElement.a (https://huit.lemonde.fr/app/main-app.986c0ae6.js:1:2929)
```

**Comment by Yvem** [comment]
solved in pending PR #9
